version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - byanat
    

  server:
    image: byanat:test
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
    networks:
      - byanat
    
  # nginx:
  #   image: nginx
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ./certs:/etc/nginx/certs
  #   depends_on:
  #     - certbot

volumes:
  postgres-data:

networks:
  byanat:
